Fix won't-compile error
18:17:34.261 Running build in Portland, USA (West) – pdx1
18:17:34.262 Build machine configuration: 2 cores, 8 GB
18:17:34.272 Cloning github.com/kevinashworth/blogr-nextjs-prisma (Branch: main, Commit: d470d8d)
18:17:34.272 Skipping build cache, deployment was triggered without cache.
18:17:34.677 Cloning completed: 405.000ms
18:17:35.068 Running "vercel build"
18:17:35.484 Vercel CLI 49.0.0
18:17:35.813 Installing dependencies...
18:17:46.745
18:17:46.745 added 146 packages in 11s
18:17:46.746
18:17:46.746 62 packages are looking for funding
18:17:46.746   run `npm fund` for details
18:17:46.786 Detected Next.js version: 12.3.7
18:17:46.790 Running "npm run build"
18:17:46.916
18:17:46.917 > blogr-nextjs-prisma@1.0.5 build
18:17:46.917 > next build
18:17:46.917
18:17:47.279 Attention: Next.js now collects completely anonymous telemetry regarding usage.
18:17:47.280 This information is used to shape Next.js' roadmap and prioritize features.
18:17:47.281 You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
18:17:47.281 https://nextjs.org/telemetry
18:17:47.281
18:17:47.374 info  - Linting and checking validity of types...
18:17:50.259 Failed to compile.
18:17:50.259
18:17:50.260 ./pages/_app.tsx:6:41
18:17:50.260 Type error: Property 'session' does not exist on type '{}'.
18:17:50.260
18:17:50.260 [0m [90m 4 | [39m[36mconst[39m [33mApp[39m [33m=[39m ({ [33mComponent[39m[33m,[39m pageProps }[33m:[39m [33mAppProps[39m) [33m=>[39m {[0m
18:17:50.260 [0m [90m 5 | [39m  [36mreturn[39m ([0m
18:17:50.260 [0m[31m[1m>[22m[39m[90m 6 | [39m    [33m<[39m[33mSessionProvider[39m session[33m=[39m{pageProps[33m.[39msession}[33m>[39m[0m
18:17:50.260 [0m [90m   | [39m                                        [31m[1m^[22m[39m[0m
18:17:50.260 [0m [90m 7 | [39m      [33m<[39m[33mComponent[39m {[33m...[39mpageProps} [33m/[39m[33m>[39m[0m
18:17:50.260 [0m [90m 8 | [39m    [33m<[39m[33m/[39m[33mSessionProvider[39m[33m>[39m[0m
18:17:50.260 [0m [90m 9 | [39m  )[33m;[39m[0m
18:17:50.309 Error: Command "npm run build" exited with 1